server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skillsync_auth
    username: skillsync
    password: skillsync
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
jwt:
  secret: skillsync-jwt-secret-key-for-development-only-change-in-prod-must-be-at-least-256-bits
  access-token-expiry-ms: 900000
  refresh-token-expiry-ms: 604800000
oauth2:
  google:
    client-id: 272230001389-v9b7bkthiupbl1rm4nffq06gm3crrs9u.apps.googleusercontent.com
  github:
    client-id: Ov23li8rLtI3EurhRc27
    client-secret: db95dde234803cae3953a6b4428223c7ebe6a37d
